const jsonInput = {};

jsonInput.celebrityList =[
    /*"Agnieszka Bednarek-Kasza",
    "Alain Decaux",
    "Alden Ehrenreich",
    "Alex Mica",
    "Alex Roe",
    "Alex Tagliani",
    "Alexander Alekhine",
    "Ali Michael",
    "Alicia Witt",
    "Anastasia Baranova",
    "Andreas Voßkuhle",
    "André Michelin",
    "Andy Burnham",
    "Angelu de Leon",
    "Anikha",
    "Anton Lesser",
    "Arnold Schwarzenegger",
    "Aruna Shields",
    "Ashleigh Barty",
    "Asma Jahangir",
    "Atsuko Inaba",
    "Ayub Bachchu",
    "B.D. Wong",
    "Bailee Madison",
    "Ben Goldwasser",
    "Ben Woodburn",
    "Benazir Bhutto",
    "Benedict Cumberbatch",
    "Bill Dance",
    "Bill Nelson",
    "Billy Eichner",
    "Bow Wow",
    "Brad Cotter",
    "Brenda Lee",
    "Brian Moses",
    "Brianna Keilar",
    "Bruce Vilanch",
    "Cacau Protásio",
    "Cameron Monaghan",
    "Candelaria Molfese",
    "Chandler Canterbury",
    "Charlie Daniels",
    "Cher",
    "Chris Colfer",
    "Chris Daughtry",
    "Chris Pine",
    "Chris Santos",
    "Christian Serratos",
    "Christina Tosi",
    "Christine Ohlman",
    "Chus Lampreave",
    "Claudia Troyo",
    "Clodagh Rodgers",
    "Colt Brennan",
    "Conchita Martínez",
    "Dan Croll",
    "Daniel Brière",
    "Daniel Kitson",
    "Daniel Murphy",
    "Daniel Padilla",
    "Daniel Rioli",
    "David Chang",
    "David Della Rocco",
    "David Hanson",
    "David Urwitz",
    "Debbie Allen",
    "Dede Yusuf",
    "Deshaun Thomas",
    "Dhruva Sarja",
    "Diane von Furstenberg",
    "Diego Maurício",
    "Dieumerci Mbokani",
    "Dmitry Chernyshenko",
    "Dominique Bertinotti",
    "Donald Woods",
    "Eddy Lover",
    "Eli Holzman",
    "Elizabeth Gillies",
    "Ellen DeGeneres",
    "Elvira Bach",
    "Emily Rose",
    "Emmanuelle Béart",
    "Eric Martin",
    "Erna Solberg",
    "Eva Briegel",
    "Éver Banega",
    "Fatima Sana Shaikh",
    "Federica Brignone",
    "Feist",
    "Felix Sturm",
    "Fergie",
    "Fumie Suguri",
    "Gary Yourofsky",
    "Gohar Rasheed",
    "Gudea",
    "Gurmeet Choudhary",
    "Gwendoline Christie",
    "Hannah Simone",
    "Hiam Abbass",
    "Ice Cube",
    "Irene Schouten",
    "Isobelle Molloy",
    "Ivana Maksimović",
    "Izaline Calister",
    "Jack Black",
    "Jack Dylan Grazer",
    "Jaime Mayor Oreja",
    "Jamelia",
    "James Beattie",
    "James Jordan",
    "James Reid",
    "James Rumbaugh",
    "Jan Eggum",
    "Jaron Lanier",
    "Jasmine Thompson",
    "Jason Alexander",
    "Jason Segel",
    "Jason Somerville",
    "Jean Batten",
    "Jeffrey Dean Morgan",
    "Jennifer Teege",
    "Jennifer Yuh Nelson",
    "Jeon So-mi",
    "Jeremy Coon",
    "Jessica Chastain",
    "Jet Bussemaker",
    "Jim Fassel",
    "Jocelyn Rae",
    "Jodie Prenger",
    "Johann André Forfang",
    "John A. Gotti",
    "John DeServio",
    "John Ehrlichman",
    "John Orozco",
    "John Redwood",
    "John Richardson",
    "John Rogers",
    "Johnny Rivers",
    "Jonah Hill",
    "Joo Sang-wook",
    "Jordan Knight",
    "Joseph Schmidt",
    "Jules Asner",
    "Julia de Burgos",
    "Jusuf Nurkić",
    "Jürgen Klopp",
    "Kaley Cuoco",
    "Karen L. Nyberg",
    "Karolina Naja",
    "Karrie Webb",
    "Katie Lou Samuelson",
    "Kel Mitchell",
    "Kendra Morris",
    "Kevin Rose",
    "Kirsty Hume",
    "Kristen Bell",
    "Kristofer Hivju",
    "Låpsley",
    "Lecy Goranson",
    "Lee Hyori",
    "Lenny Kuhr",
    "Leonard Doroftei",
    "Liam Cunningham",
    "Lilly Singh",
    "Lily Tomlin",
    "Lorraine Nicholson",
    "Louise Penny",
    "Louise Redknapp",
    "Lucinda Williams",
    "Luke Gallows",
    "Luke Perry",
    "Maharana Pratap",
    "Malik Zidi",
    "Manj Musik",
    "Mano Menezes",
    "Marcia Haydée",
    "Marcin Koszałka",
    "Marco Da Silva",
    "Marcos Witt",
    "Margaret Chase Smith",
    "Margarita Simonyan",
    "Marie Harf",
    "Marie Sebag",
    "Marie-Ange Nardi",
    "Mario",
    "Mark Eitzel",
    "Mark Sheppard",
    "Martha Graham",
    "Martin Milner",
    "Martin Petit",
    "Mary Walsh",
    "Marylouise Burke",
    "Masaki Aiba",
    "Matthew Lintz",
    "Maya Rudolph",
    "Michael Bennett",
    "Michael Collins",
    "Michael Ian Black",
    "Michal Hašek",
    "Mike Murdock",
    "Millie Bobby Brown",
    "Mirai Nagasu",
    "Mndsgn",
    "Mohammad Hafeez",
    "Muriel Rukeyser",
    "Nae Caranfil",
    "Nance Coolen",
    "Nancy Marchand",
    "Nancy O'Dell",
    "Nanjil Sampath",
    "Nellie McClung",
    "Nico Hischier",
    "Niloy Alamgir",
    "Noah Schnapp",
    "Noémie Merlant",
    "Oliver Bell",
    "Paco León",
    "Paige Hurd",
    "Pam Tillis",
    "Parvez Butt",
    "Patricia Wettig",
    "Paul Naschy",
    "Penny Taylor",
    "Pierson Fode",
    "Polly Bergen",
    "Princess Michael of Kent",
    "Professor Green",
    "Rahul Easwar",
    "Ralph Garman",
    "Rashida Jones",
    "Ravindra Jain",
    "Raymond Kvisvik",
    "Rebel Wilson",
    "Rick Elice",
    "Rita Ora",
    "Rob Verlinden",
    "Robby Mook",
    "Robert Pattinson",
    "Roberta Williams",
    "Roberto Fico",
    "Rod Fergusson",
    "Rohan Shah",
    "Romee Strijd",
    "Ron Hynes",
    "Ross Bagley",
    "Rozonda Thomas",
    "Sadie Sink",
    "Samuel Larsen",
    "Sandra Bullock",
    "Sandra Oh",
    "Sara Thunebro",
    "Scott Eastwood",
    "Sean Nelson",
    "Sean Paul",
    "Sebastian Tynkkynen",
    "Shayma Helali",
    "Shujaat Khan",
    "Sinéad Cusack",
    "So Yoo-jin",
    "SPM",
    "Stanislav Griga",
    "Steve Howey",
    "Steven Gätjen",
    "T. J. Miller",
    "Ted Danson",
    "Ted Raimi",
    "Temi Dollface",
    "Teo Teocoli",
    "Tereza Bebarová",
    "Terry McMahon",
    "Thomas Kretschmann",
    "Thomas Pesquet",
    "Tila Tequila",
    "Tkay Maidza",
    "Tobias Sammet",
    "Tom Elmhirst",
    "Tom Felton",
    "Tomas Andersson Wij",
    "Tomasz Siemoniak",
    "Tony Dallara",
    "Tony Snow",
    "Tostão",
    "Trần Đại Quang",
    "Treasure Fingers",
    "Tyler Oakley",
    "Veronika Vítková",
    "Veruska Ramírez",
    "Vesna Čitaković",
    "Véronique Sanson",
    "Violeta Urmana",
    "Von Smith",
    "Wang Xiaoli",
    "Wizkid",*/
    "Yancy Butler",
    "Yoshitomo Nara",
    "Yuen Woo-ping",
    "Yusuf Pathan",
    "Zhu Xiao-Mei",
    "Zooey Deschanel"
  ];

  module.exports = jsonInput;